local data_util = require("data_util")

-- utility sprites don't work right now so use hidden signals
data:extend({
  {
    type = "virtual-signal",
    name = data_util.mod_prefix .. "star",
    icon = "__space-exploration-graphics__/graphics/icons/astronomical/star.png",
    icon_size = 32,
    subgroup = "virtual-signal-utility",
    order = "z-a-a",
  },
  {
    type = "virtual-signal",
    name = data_util.mod_prefix .. "planet",
    icon = "__space-exploration-graphics__/graphics/icons/astronomical/planet-small.png",
    icon_size = 32,
    subgroup = "virtual-signal-utility",
    order = "z-a-b",
  },
  {
    type = "virtual-signal",
    name = data_util.mod_prefix .. "planet-orbit",
    icon = "__space-exploration-graphics__/graphics/icons/astronomical/planet-orbit.png",
    icon_size = 32,
    subgroup = "virtual-signal-utility",
    order = "z-a-b",
  },
  {
    type = "virtual-signal",
    name = data_util.mod_prefix .. "moon",
    icon = "__space-exploration-graphics__/graphics/icons/astronomical/moon-small.png",
    icon_size = 32,
    subgroup = "virtual-signal-utility",
    order = "z-a-c",
  },
  {
    type = "virtual-signal",
    name = data_util.mod_prefix .. "moon-orbit",
    icon = "__space-exploration-graphics__/graphics/icons/astronomical/moon-orbit.png",
    icon_size = 32,
    subgroup = "virtual-signal-utility",
    order = "z-a-c",
  },
  {
    type = "virtual-signal",
    name = data_util.mod_prefix .. "asteroid-belt",
    icon = "__space-exploration-graphics__/graphics/icons/astronomical/asteroid-belt.png",
    icon_size = 32,
    subgroup = "virtual-signal-utility",
    order = "z-a-d",
  },
  {
    type = "virtual-signal",
    name = data_util.mod_prefix .. "asteroid-field",
    icon = "__space-exploration-graphics__/graphics/icons/astronomical/asteroid-field.png",
    icon_size = 32,
    subgroup = "virtual-signal-utility",
    order = "z-a-e",
  },
  {
    type = "virtual-signal",
    name = data_util.mod_prefix .. "anomaly",
    icon = "__space-exploration-graphics__/graphics/icons/astronomical/anomaly.png",
    icon_size = 32,
    subgroup = "virtual-signal-utility",
    order = "z-a-f",
  },
  {
    type = "virtual-signal",
    name = data_util.mod_prefix .. "meteor",
    icon = "__space-exploration-graphics__/graphics/icons/astronomical/meteor.png",
    icon_size = 64,
    subgroup = "virtual-signal-utility",
    order = "z-a-g",
  },
  {
    type = "virtual-signal",
    name = data_util.mod_prefix .. "spaceship",
    icon = "__space-exploration-graphics__/graphics/icons/spaceship.png",
    icon_size = 32,
    subgroup = "virtual-signal-utility",
    order = "z-a-g",
  },
  {
    type = "virtual-signal",
    name = data_util.mod_prefix .. "remote-view",
    icon = "__space-exploration-graphics__/graphics/icons/shortcut-toolbar/remote-view-32-white.png",
    icon_size = 32,
    subgroup = "virtual-signal-utility",
    order = "z-z-f",
  },
  {
    type = "virtual-signal",
    name = data_util.mod_prefix .. "death",
    icon = "__space-exploration-graphics__/graphics/icons/shortcut-toolbar/respawn-32-white.png",
    icon_size = 32,
    subgroup = "virtual-signal-utility",
    order = "z-z-g",
  },
  {
    type = "virtual-signal",
    name = data_util.mod_prefix .. "character-corpse",
    icon = "__space-exploration-graphics__/graphics/icons/character-corpse.png",
    icon_size = 64,
    subgroup = "virtual-signal-utility",
    order = "z-z-h",
  },
})
